import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// Internal knowledge hub — no external links, no blog, no edit URLs.
// Page hierarchy comes from the docs/ folder structure (autogenerated sidebar).

const config: Config = {
  title: 'Team Knowledge Hub',
  tagline: 'Docs, runbooks, and guides',
  favicon: 'img/favicon.ico',

  future: {
    v4: true,
  },

  // Replace with your internal domain when deploying at the firm.
  url: 'http://localhost:3000',
  baseUrl: '/',

  onBrokenLinks: 'throw',

  customFields: {
    // Base URL of your slide-generation backend (the Python service).
    // The "Create slides" button on every doc page calls:
    //   GET  {slidesApi}/slides/status?page=<route>
    //   POST {slidesApi}/slides/generate  {"page": "<route>"}
    slidesApi: 'http://localhost:8000',
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/', // docs ARE the site — no separate landing page
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Team Knowledge Hub',
      logo: {
        alt: 'Logo',
        src: 'img/logo.svg',
      },
      items: [],
    },
    footer: {
      style: 'dark',
      links: [],
      copyright: `Internal documentation. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
