import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar is fully autogenerated from the docs/ folder structure.
// Confluence hierarchy maps 1:1 to folders:
//   Confluence:  Space > Parent Page > Child Page
//   Here:        docs/space/parent-page/child-page.mdx
// Never edit this file when adding pages — just place files in the right folder.
// Use _category_.json inside a folder to control its label and position.

const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
